### PR TITLE
minty for pkgdown!

### PR DESCRIPTION
**Pull request by gadenbuie**
I ported the [Bootswatch Minty theme](https://bootswatch.com/minty/) to Bootstrap v3 because you're right, it is awesome.

Screenshot_2019-08-09 Client for the Toronto Open Data Portal API(2)

I did it quickly so it's not a perfect port, but it's pretty close. I used [themestrap](https://github.com/divshot/themestrap) to get it started but bumped the Bootstrap version to `3.3.7`. I also put the final theme in [gadenbuie/bootstrap-v3-theme-minty](https://github.com/gadenbuie/boostrap-v3-theme-minty) in case it needs tweaking. (And please don't feel any pressure to use the theme.)

For this PR I moved `_pkgdown.yml` into `pkgdown/` and added the theme there as `extra.css`. This is the quick-and-dirty way of overriding the full theme, see https://github.com/r-lib/pkgdown/issues/987 for more ideas about how to do this.

Enjoy!

### CODE REVIEW

**Comment by sharlagelfand** [comment]
thank you!! this is so amazing 😻 do you happen to know how to do the inverse navbar? as you might imagine, i have some interest in having it use the pink instead of the green 😁

**Comment by gadenbuie** [comment]
No problem! I thought you might like the pink, try adding this to `_pkgdown.yml`

```yaml
navbar:
  type: inverse
```

**Comment by sharlagelfand** [comment]
thanks! i wasn't sure if that would work like it does normally in pkgdown since it's a custom theme 😋 guess i should have at least tried! thank you so much, seriously

**Comment by gadenbuie** [comment]
I was pleasantly surprised it worked too 😄 the minty pink looks rad! :sunglasses:

**Pull request merged**
